apiVersion: v1
kind: Secret
metadata:
  name: cineverse-secrets
  namespace: cineverse-production
type: Opaque
stringData:
  DATABASE_URL: "postgresql://cineverse_prod_user:p4ssw0rd_prod_992@prod-postgres.cineverse.internal:5432/cineverse_db"
  REDIS_URL: "redis://:prod_redis_pass_992@prod-redis.cineverse.internal:6379"
  JWT_SECRET: "prod_jwt_super_secret_key_cineverse_2026_enterprise_99"
  STRIPE_SECRET_KEY: "sk_live_cineverse_enterprise_production_key"
  GEMINI_API_KEY: "AIzaSyCineverseEnterpriseProductionKeyGemini2026"
